// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrIyEEn8Ozz-cEU_7RTjWHoN1SQb4KTKg',
    appId: '1:1029881561828:web:5beadde81d4c03e606e2f1',
    messagingSenderId: '1029881561828',
    projectId: 'tos-merl-app',
    authDomain: 'tos-merl-app.firebaseapp.com',
    storageBucket: 'tos-merl-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWa2XhyD3aOAmwr_sn1tjgJwc4WlzeGSg',
    appId: '1:1029881561828:android:6153f44bdc1b66cf06e2f1',
    messagingSenderId: '1029881561828',
    projectId: 'tos-merl-app',
    storageBucket: 'tos-merl-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoxdNnJ4nJjmVR87UkU9PhIkA8IKGvJO0',
    appId: '1:1029881561828:ios:86249fd463f597eb06e2f1',
    messagingSenderId: '1029881561828',
    projectId: 'tos-merl-app',
    storageBucket: 'tos-merl-app.firebasestorage.app',
    iosBundleId: 'com.example.tosMerl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoxdNnJ4nJjmVR87UkU9PhIkA8IKGvJO0',
    appId: '1:1029881561828:ios:86249fd463f597eb06e2f1',
    messagingSenderId: '1029881561828',
    projectId: 'tos-merl-app',
    storageBucket: 'tos-merl-app.firebasestorage.app',
    iosBundleId: 'com.example.tosMerl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrIyEEn8Ozz-cEU_7RTjWHoN1SQb4KTKg',
    appId: '1:1029881561828:web:31c8dd417997775806e2f1',
    messagingSenderId: '1029881561828',
    projectId: 'tos-merl-app',
    authDomain: 'tos-merl-app.firebaseapp.com',
    storageBucket: 'tos-merl-app.firebasestorage.app',
  );
}
